### ISSUE TITLE
Suggestions for improvment for support script collection:

### ISSUE THREAD

**Issue by MartyEwings** [puppetlabs/puppetlabs-pe_quick_data#24]
May be worth changing this to "1" as to limit the size of the return if we only need a "current" snapshot

https://github.com/puppetlabs/puppetlabs-pe_quick_data/blob/c9be77b61f445b60de0666d219af36aa58530678/tasks/collect.sh#L65

The HCL tag here I believe may be a remnant from the Health Check light script, we could change it to something like "pe_quick_data" or even leave it out.

https://github.com/puppetlabs/puppetlabs-pe_quick_data/blob/182f4206d95ebd1beca4a3275bd4bfca70a35b70/tasks/collect.sh#L68

similar with reference to tech check:

https://github.com/puppetlabs/puppetlabs-pe_quick_data/blob/c9be77b61f445b60de0666d219af36aa58530678/tasks/collect.sh#L107

**Comment by moedes** [comment]
Resolved in version 1.2.0.    Removed has_opt '--ticket' && sup_args+=("--ticket" "${ticket:-HCL}") completely, change the language of the status output for the collect.sh task and disabled logging by default.
