### ISSUE TITLE
Dynamically lookup code dir instead of statically assiging

### ISSUE THREAD

**Issue by MartyEwings** [puppetlabs/puppetlabs-pe_quick_data#25]
99.9% of customers use the default, but some of the puppetdirs can be changed from the default locations,

so it may be better to define these lines like this:

ls -1 $(puppet config print codedir)/environments

https://github.com/puppetlabs/puppetlabs-pe_quick_data/blob/c9be77b61f445b60de0666d219af36aa58530678/tasks/site_modules.sh#L5

**Comment by moedes** [comment]
Added in 1.2.0
